check:
	g++ -o ../build/main main.cpp -lncurses -std=c++2a -O2
	rm ../build/main
build:
	g++ -o ../build/main main.cpp -lncurses -std=c++2a -O2
test:
	g++ -o ../build/main main.cpp -lncurses -std=c++2a -O2
	../build/main ../testfiles/mainTest.cpp

smallTest:
	g++ -o ../build/main main.cpp -lncurses -std=c++2a -O2
	../build/main ../testfiles/smallTest.cpp
